#!/bin/bash
# Quick reference for where to find environment variable values

echo "=========================================="
echo "Environment Variable Quick Reference Guide"
echo "=========================================="
echo ""
echo "🔐 SECRETS & AUTHENTICATION:"
echo "  SHARED_SECRET:"
echo "    - Check existing .env.backup.*"
echo "    - Check team password manager"
echo "    - Ask team lead if not found"
echo ""
echo "🗄️ DATABASE:"
echo "  DATABASE_URL:"
echo "    - Check existing .env.backup.*"
echo "    - Format: postgresql://user:pass@host:port/dbname"
echo "    - Get from database provider dashboard (e.g., Supabase)"
echo ""
echo "☁️ CLOUDFLARE:"
echo "  CF_ACCOUNT_ID:"
echo "    - Login to Cloudflare Dashboard"
echo "    - Look at right sidebar for Account ID"
echo ""
echo "  CF_API_TOKEN_WORKERS & CF_API_TOKEN_R2:"
echo "    - Cloudflare Dashboard > My Profile > API Tokens"
echo "    - Create token with Workers/R2 permissions if needed"
echo ""
echo "  R2 Storage (R2_BUCKET_NAME, R2_ACCESS_KEY_ID, etc):"
echo "    - Cloudflare Dashboard > R2"
echo "    - Select your bucket > Settings"
echo "    - Manage R2 API Tokens for access keys"
echo ""
echo "  CF_KV_NAMESPACE_ID:"
echo "    - Cloudflare Dashboard > Workers & Pages > KV"
echo "    - Copy the ID of your namespace"
echo ""
echo "  CF_PAGES_PROJECT_NAME:"
echo "    - Cloudflare Dashboard > Pages"
echo "    - Your project name exactly as shown"
echo ""
echo "  CF_PAGES_PROJECT_ID:"
echo "    - Cloudflare Dashboard > Pages > Your Project > Settings"
echo "    - Project ID shown in settings"
echo ""
echo "  CF_ZONE_ID:"
echo "    - Cloudflare Dashboard > Your Domain > Overview"
echo "    - Zone ID in right sidebar"
echo ""
echo "🔄 REDIS:"
echo "  REDIS_URL or REDIS_HOST/REDIS_PORT:"
echo "    - Default local: redis://localhost:6379"
echo "    - Production: Check with DevOps team"
echo "    - Must have Redis running locally for development"
echo ""
echo "📊 OPTIONAL SERVICES:"
echo "  OpenTelemetry: Usually http://127.0.0.1:4318 for local"
echo "  AWS: Check AWS Console for region and services"
echo ""
echo "🏗️ ARCHITECTURE:"
echo "  ARCH_MODE: Currently using 'stream' in production"
echo "  SKIP_QUEUE: Set to 'true' to bypass Redis queues"
echo "  DIRECT_MODE: Set to 'true' for synchronous processing"
echo ""
echo "⚠️  NEVER commit real values to git!"
echo "✅ Use 'npm run validate:env' to check your configuration"
echo "📋 Check existing .env for current working values"
echo ""