-- Voice Recordings: Hero page support + analytics + idempotency
--
-- IMPORTANT: Review before running in production
--
-- Changes:
-- 1. Add client_recording_id for true idempotency (generated at recording start)
-- 2. Make project_id nullable (hero page has no project)
-- 3. Add source column for analytics (hero, project, api, etc.)
-- 4. Update RLS policies for INSERT and UPDATE (UPSERT needs both!)
-- 5. Add indexes for analytics queries
--
-- After this migration:
-- - All recordings saved to DB (hero page included)
-- - source column tracks entry point for product analytics
-- - client_recording_id prevents duplicates on double-tap/retry
--
-- Note on backfill: This migration does UPDATE + SET NOT NULL which can lock
-- the table briefly. Safe for small tables. For large tables (100k+ rows),
-- consider batching the UPDATE or using a NOT VALID constraint pattern.
--
-- Created: 2026-01-19
-- Status: READY FOR REVIEW

-- ============================================================================
-- 1. Add client_recording_id for idempotency
-- ============================================================================
-- Generated by frontend at recording START, used in storage path and DB
-- This is the TRUE idempotency key (not audio_url which varies on retry)

ALTER TABLE voice_recordings
  ADD COLUMN IF NOT EXISTS client_recording_id uuid;

-- Backfill existing records with generated UUIDs (one-time)
UPDATE voice_recordings
SET client_recording_id = gen_random_uuid()
WHERE client_recording_id IS NULL;

-- Now make it NOT NULL for new records
ALTER TABLE voice_recordings
  ALTER COLUMN client_recording_id SET NOT NULL;

-- ============================================================================
-- 2. Make project_id nullable
-- ============================================================================
-- Hero page recordings don't have a project context

ALTER TABLE voice_recordings
  ALTER COLUMN project_id DROP NOT NULL;

-- ============================================================================
-- 3. Add source column for analytics
-- ============================================================================
-- Tracks where the recording originated for product analytics
-- CHECK constraint prevents typos/invalid values

ALTER TABLE voice_recordings
  ADD COLUMN IF NOT EXISTS source text NOT NULL DEFAULT 'project'
  CHECK (source IN ('hero', 'project', 'workspace', 'api', 'mobile'));

-- ============================================================================
-- 4. Update RLS policies for INSERT and UPDATE
-- ============================================================================
-- CRITICAL: UPSERT requires BOTH INSERT and UPDATE policies!
-- Without UPDATE policy, ON CONFLICT DO UPDATE will fail silently.

-- Drop old policy that requires project ownership check
DROP POLICY IF EXISTS "Users can create voice recordings for own projects" ON voice_recordings;

-- INSERT policy: allow insert for own recordings (with or without project)
CREATE POLICY "Users can create voice recordings"
  ON voice_recordings FOR INSERT
  WITH CHECK (
    auth.uid() = user_id
    AND (
      project_id IS NULL  -- Allow recordings without project (hero page)
      OR EXISTS (          -- Or require project ownership
        SELECT 1 FROM projects
        WHERE id = voice_recordings.project_id
        AND owner_id = auth.uid()
      )
    )
  );

-- UPDATE policy: required for UPSERT's ON CONFLICT DO UPDATE
-- Users can only update their own recordings
DROP POLICY IF EXISTS "Users can update voice recordings" ON voice_recordings;

CREATE POLICY "Users can update voice recordings"
  ON voice_recordings FOR UPDATE
  USING (auth.uid() = user_id)
  WITH CHECK (auth.uid() = user_id);

-- ============================================================================
-- 5. Add indexes
-- ============================================================================

-- Unique constraint on (user_id, client_recording_id) for UPSERT idempotency
-- This is what prevents duplicates on double-tap stop or network retry
CREATE UNIQUE INDEX IF NOT EXISTS idx_voice_recordings_user_client_id_unique
  ON voice_recordings(user_id, client_recording_id);

-- Index for analytics queries (dashboards, funnels)
-- Covers: SELECT ... WHERE source = 'hero' ORDER BY created_at DESC
CREATE INDEX IF NOT EXISTS idx_voice_recordings_source_created_at
  ON voice_recordings(source, created_at DESC);

-- Drop old audio_url index (no longer used for idempotency)
DROP INDEX IF EXISTS idx_voice_recordings_user_audio_url_unique;

-- ============================================================================
-- Notes for code changes after running this migration:
-- ============================================================================
--
-- 1. voice-recording-modal.tsx:
--    - Generate recordingId at recording START (not in uploadToStorage)
--    - Pass recordingId to uploadToStorage and API
--    - Storage path: {userId}/{year}/{month}/{recordingId}.{ext}
--
-- 2. /api/v1/transcribe:
--    - Always save to DB (remove projectId check)
--    - Set source = projectId ? 'project' : 'hero'
--    - UPSERT on (user_id, client_recording_id)
--
-- 3. Future: "Attach" hero recordings to project after creation
--    UPDATE voice_recordings
--    SET project_id = $new_project_id, source = 'project'
--    WHERE user_id = $user_id AND project_id IS NULL
--      AND source = 'hero' AND created_at > now() - interval '7 days';
--
